apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-image-build-pipeline.yaml
  - backend-image-build-pipeline.yaml
  - frontend-sonarqube-pipeline.yaml
  - backend-sonarqube-pipeline.yaml
  - pvc.yaml
